### PR TITLE
Create Coordinates.swift

### PR DESCRIPTION
**Pull request by ghost**
Use like this:

```swift
var view = UIView(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
view.convertToCenter(CGPoint(x: 0, y: 0)) == CGPoint(x: 50, y: 50) // true
``` 
You can also define custom overloads using the `CoordConvertible` protocol. This is how `MyStruct` is defined:

```swift
struct MyStruct: CoordConvertible {
  typealias Point = MyPoint
  static let coordinateSystem: CoordSystem == .originCenter
}
```

For free you get the static method `convert(_:to:bounds:)`, and if you also conform to `SizeType` you one extra instance method.

```swift
// The free static method
MyStruct.convert(myPoint, to: .originTopLeft, bounds: someBounds)

// SizeType
extension MyStruct: SizeType {
 var width = ...
 var height = ...
}

myStruct.convert(myPoint, to: .originTopLeft)
```

All of the standard CoreGraphics types conform to the protocols, so for example `CGRect` is a `RectType` and UIViews conform to `CoordConvertible` and `SizeType`.

### CODE REVIEW

**Comment by SafelySwift** [comment]
Can we discuss this? I have two remarks about it:

1. The whole `-Type` suffixes feel like Swift 2.
2. The `CoordConvertible` has a misleading name: unlike `CustomStringConvertible` or others, it does not convert into points, but rather does the conversion. Should we rename it `CoordConverting`?

**Comment by tattn** [comment]
It's an interesting function 👍 

> 1. The whole -Type suffixes feel like Swift 2.

You have a point! But I can't think of any better idea. I think -Type suffix is not bad naming :-D

> The CoordConvertible has a misleading name: unlike CustomStringConvertible or others, it does not convert into points, but rather does the conversion. Should we rename it CoordConverting?

-ing suffix like `UIViewControllerAnimatedTransitioning` is also good. But I prefer `CoordConvertible` because resembling the standard name means Apple-way!

**Comment by SafelySwift** [comment]
I am thinking about adding another clause so that `NSView` supports this `CoordConvertible` protocol.

**Comment by tattn** [comment]
Please add `Coordinates.swift` to the project.

**Pull request closed without merging**
